/**
 * BETA OFFICE — Experiment Manifest
 * Static metadata for every experiment — id/name/category/description/
 * number/file — loaded eagerly so tiles, search (js/help.js), and the
 * command palette can list and filter all 99 before any experiment's
 * actual script (js/experiments/*.js) has loaded. Each one is fetched
 * on demand instead (see registry.js's loadExperiment()), the first
 * time it's actually opened — see the file field below.
 *
 * Generated from each experiment module's own registerExperiment()
 * call. If you add a new experiment, add its entry here too (same id/
 * name/category/description/number as the module itself) — this list
 * is what makes it discoverable before its script has ever run.
 */
(function () {
  if (!window.BetaExperiments) return;

  window.BetaExperiments.registerManifest([
    { id: "typography", name: "Typography", category: "PAGEFX", description: "Size, spacing, line-height, scramble", number: 1, file: "typography.js" },
    { id: "motion", name: "Motion", category: "PAGEFX", description: "Spring, attract, repel, float", number: 2, file: "motion.js" },
    { id: "cursor", name: "Cursor", category: "PAGEFX", description: "Crosshair, circle, coords, trailing", number: 3, file: "cursor.js" },
    { id: "grid", name: "Grid", category: "PAGEFX", description: "Column, baseline, pixel overlays", number: 4, file: "grid.js" },
    { id: "color", name: "Color", category: "PAGEFX", description: "Background, foreground, invert, mono", number: 5, file: "color.js" },
    { id: "dom", name: "DOM", category: "DEVTOOLS", description: "Outline, bounds, live node count", number: 6, file: "dom.js" },
    { id: "browser", name: "Browser", category: "DEVTOOLS", description: "Viewport, DPR, scroll, mouse, FPS, UA", number: 7, file: "browser.js" },
    { id: "system", name: "System", category: "DEVTOOLS", description: "Build, registry, open windows", number: 8, file: "system.js" },
    { id: "debug", name: "Debug", category: "DEVTOOLS", description: "Registry dump", number: 9, file: "debug.js" },
    { id: "image", name: "Image", category: "DEVTOOLS", description: "Drop a file, grayscale/invert/blur", number: 10, file: "image.js" },
    { id: "sound", name: "Sound", category: "SOUND", description: "Oscillator beep, freq/volume", number: 11, file: "sound.js" },
    { id: "canvas", name: "Canvas", category: "VISUAL", description: "Freehand draw, brush size, clear", number: 12, file: "canvas.js" },
    { id: "physics", name: "Physics", category: "PAGEFX", description: "Gravity + bounce ball-pit", number: 13, file: "physics.js" },
    { id: "distortion", name: "Distortion", category: "PAGEFX", description: "Skew, perspective tilt, shake", number: 14, file: "distortion.js" },
    { id: "snake", name: "Snake", category: "GAMES", description: "Grid snake, arrow keys, score", number: 15, file: "snake.js" },
    { id: "reflex", name: "Reflex", category: "SKILL", description: "Click-to-arm reaction timer, best/last ms", number: 16, file: "reflex.js" },
    { id: "confetti", name: "Confetti", category: "VISUAL", description: "Click to burst, count + gravity sliders", number: 17, file: "confetti.js" },
    { id: "pong", name: "Pong", category: "GAMES", description: "Solo paddle-and-wall, mouse control, streak score", number: 18, file: "pong.js" },
    { id: "memory", name: "Memory", category: "GAMES", description: "Flip-and-match card grid, move counter", number: 19, file: "memory.js" },
    { id: "whack", name: "Whack", category: "GAMES", description: "30s timed mole-grid clicker, score", number: 20, file: "whack.js" },
    { id: "fortune", name: "Fortune", category: "WORDPLAY", description: "Click for a one-line fortune", number: 21, file: "fortune.js" },
    { id: "dice", name: "Dice", category: "GAMES", description: "Click to roll, flicker settle, history", number: 22, file: "dice.js" },
    { id: "piano", name: "Piano", category: "SOUND", description: "Click or A S D F H J K L to play", number: 23, file: "piano.js" },
    { id: "simon", name: "Simon", category: "GAMES", description: "Watch, then repeat the flashing sequence", number: 24, file: "simon.js" },
    { id: "tictactoe", name: "TicTacToe", category: "GAMES", description: "Local 2-player 3x3 grid, no AI", number: 25, file: "tictactoe.js" },
    { id: "minesweeper", name: "Minesweeper", category: "GAMES", description: "8x8 grid, flag with right-click, avoid the mines", number: 26, file: "minesweeper.js" },
    { id: "2048", name: "2048", category: "GAMES", description: "Arrow-key slide and merge, reach 2048", number: 27, file: "2048.js" },
    { id: "connectfour", name: "Connect Four", category: "GAMES", description: "Local 2-player, click a column to drop", number: 28, file: "connectfour.js" },
    { id: "breakout", name: "Breakout", category: "GAMES", description: "Mouse paddle, break every brick", number: 29, file: "breakout.js" },
    { id: "hangman", name: "Hangman", category: "GAMES", description: "Guess the word, 6 wrong guesses allowed", number: 30, file: "hangman.js" },
    { id: "lightsout", name: "Lights Out", category: "GAMES", description: "Click toggles a cell + neighbors, turn them all off", number: 31, file: "lightsout.js" },
    { id: "maze", name: "Maze", category: "GAMES", description: "Arrow keys to the exit, timed", number: 32, file: "maze.js" },
    { id: "slots", name: "Slots", category: "GAMES", description: "Spin 3 reels, match all 3 to win", number: 33, file: "slots.js" },
    { id: "wheel", name: "Wheel", category: "GAMES", description: "Spin to pick from a list of options", number: 34, file: "wheel.js" },
    { id: "hilo", name: "HiLo", category: "GAMES", description: "Guess higher or lower, build a streak", number: 35, file: "hilo.js" },
    { id: "bingo", name: "Bingo", category: "GAMES", description: "Random 5x5 card, click to mark, get a line", number: 36, file: "bingo.js" },
    { id: "rockpaperscissors", name: "Rock Paper Scissors", category: "GAMES", description: "Endless rounds vs the computer, W/L/T tally", number: 37, file: "rockpaperscissors.js" },
    { id: "guessnumber", name: "Guess Number", category: "GAMES", description: "1-100, higher/lower hints, fewest guesses", number: 38, file: "guessnumber.js" },
    { id: "scramble", name: "Scramble", category: "WORDPLAY", description: "Unscramble the word, keep the streak", number: 39, file: "scramble.js" },
    { id: "trivia", name: "Trivia", category: "WORDPLAY", description: "Multiple-choice questions, running score", number: 40, file: "trivia.js" },
    { id: "math", name: "Math", category: "WORDPLAY", description: "30s of quick arithmetic, score", number: 41, file: "math.js" },
    { id: "emojiguess", name: "Emoji Guess", category: "WORDPLAY", description: "Guess the phrase from the emoji", number: 42, file: "emojiguess.js" },
    { id: "cps", name: "CPS", category: "SKILL", description: "Click as fast as you can for 5 seconds", number: 43, file: "cps.js" },
    { id: "typerace", name: "Type Race", category: "WORDPLAY", description: "Type the sentence, get your WPM", number: 44, file: "typerace.js" },
    { id: "fireworks", name: "Fireworks", category: "VISUAL", description: "Auto-looping rocket launch and burst", number: 45, file: "fireworks.js" },
    { id: "starfield", name: "Starfield", category: "VISUAL", description: "Warp-speed starfield, speed slider", number: 46, file: "starfield.js" },
    { id: "matrixrain", name: "Matrix Rain", category: "VISUAL", description: "Falling glyph columns, speed slider", number: 47, file: "matrixrain.js" },
    { id: "gameoflife", name: "Game of Life", category: "VISUAL", description: "Conway's life — click to seed, play/pause", number: 48, file: "gameoflife.js" },
    { id: "fractaltree", name: "Fractal Tree", category: "VISUAL", description: "Recursive branching tree, angle + depth sliders", number: 49, file: "fractaltree.js" },
    { id: "kaleidoscope", name: "Kaleidoscope", category: "VISUAL", description: "Mouse-driven mirrored symmetric drawing", number: 50, file: "kaleidoscope.js" },
    { id: "lavalamp", name: "Lava Lamp", category: "VISUAL", description: "Ambient drifting blurred blobs", number: 51, file: "lavalamp.js" },
    { id: "spirograph", name: "Spirograph", category: "VISUAL", description: "Parametric curve, R/r/d sliders", number: 52, file: "spirograph.js" },
    { id: "gravitywells", name: "Gravity Wells", category: "VISUAL", description: "Click to place attractors, particles orbit", number: 53, file: "gravitywells.js" },
    { id: "constellation", name: "Constellation", category: "VISUAL", description: "Click to place stars, auto-linked to the nearest", number: 54, file: "constellation.js" },
    { id: "textblast", name: "Text Blast", category: "VISUAL", description: "Click the text to explode and reform it", number: 55, file: "textblast.js" },
    { id: "banner", name: "Banner", category: "VISUAL", description: "Type text, see it rendered huge", number: 56, file: "banner.js" },
    { id: "palette", name: "Palette", category: "VISUAL", description: "Generate a 5-color swatch, click to copy", number: 57, file: "palette.js" },
    { id: "bubblewrap", name: "Bubble Wrap", category: "VISUAL", description: "Click to pop every bubble", number: 58, file: "bubblewrap.js" },
    { id: "balloons", name: "Balloons", category: "VISUAL", description: "Pop rising balloons before they float off, 3 lives", number: 59, file: "balloons.js" },
    { id: "drums", name: "Drums", category: "SOUND", description: "8-step 3-track beat sequencer", number: 60, file: "drums.js" },
    { id: "metronome", name: "Metronome", category: "SOUND", description: "BPM slider, visual + audio tick", number: 61, file: "metronome.js" },
    { id: "soundboard", name: "Soundboard", category: "SOUND", description: "8 preset one-shot tones", number: 62, file: "soundboard.js" },
    { id: "timer", name: "Timer", category: "UTILITY", description: "Countdown timer, beeps at zero", number: 63, file: "timer.js" },
    { id: "stopwatch", name: "Stopwatch", category: "UTILITY", description: "Start, stop, lap, reset", number: 64, file: "stopwatch.js" },
    { id: "coinflip", name: "Coin Flip", category: "GAMES", description: "Animated flip, heads/tails tally", number: 65, file: "coinflip.js" },
    { id: "textmirror", name: "Text Mirror", category: "VISUAL", description: "Type text, see it reversed/flipped/mirrored", number: 66, file: "textmirror.js" },
    { id: "pixelpaint", name: "Pixel Paint", category: "VISUAL", description: "16x16 grid, click-drag to paint", number: 67, file: "pixelpaint.js" },
    { id: "stickynotes", name: "Sticky Notes", category: "UTILITY", description: "Add draggable sticky notes, edit inline", number: 68, file: "stickynotes.js" },
    { id: "buzzword", name: "Buzzword", category: "WORDPLAY", description: "Click for a corporate-jargon phrase", number: 69, file: "buzzword.js" },
    { id: "startupname", name: "Startup Name", category: "WORDPLAY", description: "Click for a fake startup name", number: 70, file: "startupname.js" },
    { id: "stroop", name: "Stroop", category: "WORDPLAY", description: "Click the ink color, not the word", number: 71, file: "stroop.js" },
    { id: "flock", name: "Flock", category: "VISUAL", description: "Simple boids flocking simulation", number: 72, file: "flock.js" },
    { id: "moodring", name: "Focused", category: "VISUAL", description: "Click for a random mood + color", number: 73, file: "moodring.js" },
    { id: "rubberduck", name: "Rubber Duck", category: "UTILITY", description: "Explain your problem, the duck listens", number: 74, file: "rubberduck.js" },
    { id: "wordcloud", name: "Word Cloud", category: "WORDPLAY", description: "Paste text, see a word-frequency cloud", number: 75, file: "wordcloud.js" },
    { id: "stacker", name: "Stacker", category: "GAMES", description: "Click to drop blocks, don't overflow a column", number: 76, file: "stacker.js" },
    { id: "airhockey", name: "Air Hockey", category: "GAMES", description: "Mouse paddle vs a simple AI, first to 5", number: 77, file: "airhockey.js" },
    { id: "battleship", name: "Battleship", category: "GAMES", description: "Click cells to find and sink the hidden fleet", number: 78, file: "battleship.js" },
    { id: "fishtank", name: "Fish Tank", category: "VISUAL", description: "Ambient swimming fish, click to add more", number: 79, file: "fishtank.js" },
    { id: "snow", name: "Snow", category: "VISUAL", description: "Ambient falling snow", number: 80, file: "snow.js" },
    { id: "colorpicker", name: "Color Picker", category: "VISUAL", description: "Click the gradient to sample its exact color", number: 81, file: "colorpicker.js" },
    { id: "dotsandboxes", name: "Dots and Boxes", category: "GAMES", description: "Local 2-player — claim edges, complete boxes to score", number: 82, file: "dotsandboxes.js" },
    { id: "wordle", name: "Wordle", category: "GAMES", description: "Guess the 5-letter word in 6 tries", number: 83, file: "wordle.js" },
    { id: "blackjack", name: "Blackjack", category: "GAMES", description: "Hit or stand against the dealer, beat 21", number: 84, file: "blackjack.js" },
    { id: "audioreflex", name: "Audio Reflex", category: "SOUND", description: "Click Arm, then press Space the instant you hear the beep", number: 85, file: "audioreflex.js" },
    { id: "pendulum", name: "Pendulum", category: "VISUAL", description: "Drag the bob to set an angle, release to swing", number: 86, file: "pendulum.js" },
    { id: "bigclock", name: "Big Clock", category: "UTILITY", description: "A live, oversized digital clock", number: 87, file: "bigclock.js" },
    { id: "breathe", name: "Breathe", category: "UTILITY", description: "A slow, guided breathing circle", number: 88, file: "breathe.js" },
    { id: "plinko", name: "Plinko", category: "GAMES", description: "Drop a ball through the pegs into a scoring slot", number: 89, file: "plinko.js" },
    { id: "target", name: "Target", category: "SKILL", description: "Click the target before it shrinks away, score streak", number: 90, file: "target.js" },
    { id: "slidepuzzle", name: "Slide Puzzle", category: "GAMES", description: "Classic 15-puzzle — slide tiles into numeric order", number: 91, file: "slidepuzzle.js" },
    { id: "hanoi", name: "Tower of Hanoi", category: "GAMES", description: "Click a peg to pick up, click another to place", number: 92, file: "hanoi.js" },
    { id: "worddrop", name: "Word Drop", category: "WORDPLAY", description: "Type falling words before they land", number: 93, file: "worddrop.js" },
    { id: "tonguetwister", name: "Tongue Twister", category: "WORDPLAY", description: "Click for a tongue twister, say it 3 times fast", number: 94, file: "tonguetwister.js" },
    { id: "riddle", name: "Riddle", category: "WORDPLAY", description: "Click for a riddle, click again to reveal the answer", number: 95, file: "riddle.js" },
    { id: "wouldyourather", name: "Would You Rather", category: "WORDPLAY", description: "Click a side to vote, tallied just for fun", number: 96, file: "wouldyourather.js" },
    { id: "spinner", name: "Spinner", category: "VISUAL", description: "Drag in a circle to flick the spinner, watch it slow down", number: 97, file: "spinner.js" },
    { id: "etchasketch", name: "Etch A Sketch", category: "VISUAL", description: "Two knobs move the pen — X and Y sliders draw a line", number: 98, file: "etchasketch.js" },
    { id: "experiments-index", name: "Experiments", category: "EXPERIMENTS", description: "Every tool, one list", number: 99, file: "experiments-index.js" },
  ]);
})();
